require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const mongoose = require("mongoose");
const AptitudeQuestion = require("../models/AptitudeQuestion");

const initialQuestions = [
  // =========================================================================
  // QUANTITATIVE APTITUDE (25 Questions)
  // =========================================================================
  {
    question: "If A's salary is 25% more than B's salary, by what percentage is B's salary less than A's?",
    options: ["15%", "20%", "25%", "30%"],
    correctAnswer: 1,
    explanation: "Let B's salary be $100. A's salary = $125. B's salary is $25 less than A's. Percentage less = (25 / 125) * 100 = 20%.",
    category: "Quantitative Aptitude",
    topic: "Percentage",
    difficulty: "easy",
  },
  {
    question: "A student scored 30% marks and failed by 15 marks. Another student scored 40% marks and obtained 35 marks more than the pass marks. What is the maximum mark?",
    options: ["300", "400", "500", "600"],
    correctAnswer: 2,
    explanation: "Let maximum mark be M. Difference in percentage = 40% - 30% = 10%. Difference in marks = 35 - (-15) = 50 marks. 10% of M = 50 => M = 500.",
    category: "Quantitative Aptitude",
    topic: "Percentage",
    difficulty: "medium",
  },
  {
    question: "The population of a town increases by 10% annually. If the current population is 20,000, what will it be after 2 years?",
    options: ["22,000", "24,000", "24,200", "25,000"],
    correctAnswer: 2,
    explanation: "Population after 2 years = 20,000 * (1 + 10/100)^2 = 20,000 * 1.21 = 24,200.",
    category: "Quantitative Aptitude",
    topic: "Percentage",
    difficulty: "easy",
  },
  {
    question: "An item is sold for $480 at a loss of 20%. At what price should it be sold to gain 20%?",
    options: ["$600", "$680", "$720", "$800"],
    correctAnswer: 2,
    explanation: "Selling Price at 20% loss = 80% of Cost Price (CP) = $480 => CP = 480 / 0.8 = $600. To gain 20%, Selling Price = 1.2 * 600 = $720.",
    category: "Quantitative Aptitude",
    topic: "Profit and Loss",
    difficulty: "easy",
  },
  {
    question: "The cost price of 15 articles is equal to the selling price of 10 articles. What is the profit percentage?",
    options: ["25%", "33.33%", "50%", "66.66%"],
    correctAnswer: 2,
    explanation: "Let CP of 1 article = $1. CP of 10 articles = $10. SP of 10 articles = CP of 15 articles = $15. Profit = 15 - 10 = $5. Profit % = (5 / 10) * 100 = 50%.",
    category: "Quantitative Aptitude",
    topic: "Profit and Loss",
    difficulty: "medium",
  },
  {
    question: "Two numbers are in the ratio 3:5. If 9 is subtracted from each, the new numbers are in the ratio 12:23. What is the smaller number?",
    options: ["27", "33", "36", "55"],
    correctAnswer: 1,
    explanation: "Let numbers be 3x and 5x. (3x - 9) / (5x - 9) = 12 / 23. Cross-multiplying: 23(3x - 9) = 12(5x - 9) => 69x - 207 = 60x - 108 => 9x = 99 => x = 11. Smaller number = 3 * 11 = 33.",
    category: "Quantitative Aptitude",
    topic: "Ratio and Proportion",
    difficulty: "hard",
  },
  {
    question: "Divide $1,200 among A, B, and C in the ratio 2:3:5. What is B's share?",
    options: ["$240", "$360", "$400", "$600"],
    correctAnswer: 1,
    explanation: "Total parts = 2 + 3 + 5 = 10 parts. Value of 1 part = 1200 / 10 = $120. B's share = 3 * 120 = $360.",
    category: "Quantitative Aptitude",
    topic: "Ratio and Proportion",
    difficulty: "easy",
  },
  {
    question: "The average weight of 8 persons increases by 2.5 kg when a new person replaces one weighing 65 kg. What is the weight of the new person?",
    options: ["75 kg", "80 kg", "85 kg", "90 kg"],
    correctAnswer: 2,
    explanation: "Total weight increase = 8 * 2.5 = 20 kg. Weight of new person = weight of replaced person + increase = 65 + 20 = 85 kg.",
    category: "Quantitative Aptitude",
    topic: "Average",
    difficulty: "medium",
  },
  {
    question: "The average of 5 consecutive odd numbers is 27. What is the highest number?",
    options: ["27", "29", "31", "33"],
    correctAnswer: 2,
    explanation: "In a set of consecutive odd numbers, the middle number is the average. The numbers are 23, 25, 27, 29, 31. The highest number is 31.",
    category: "Quantitative Aptitude",
    topic: "Average",
    difficulty: "easy",
  },
  {
    question: "A can complete a piece of work in 12 days and B can complete it in 24 days. Working together, in how many days can they complete the work?",
    options: ["6 days", "8 days", "9 days", "10 days"],
    correctAnswer: 1,
    explanation: "A's 1 day work = 1/12. B's 1 day work = 1/24. Combined 1 day work = 1/12 + 1/24 = 3/24 = 1/8. Total time = 8 days.",
    category: "Quantitative Aptitude",
    topic: "Time and Work",
    difficulty: "easy",
  },
  {
    question: "A and B can do a work in 10 days and 15 days respectively. They worked together for 4 days, then A left. How many days will B take to finish the remaining work?",
    options: ["3 days", "5 days", "6 days", "8 days"],
    correctAnswer: 1,
    explanation: "Combined 1 day work = 1/10 + 1/15 = 1/6. Work done in 4 days = 4/6 = 2/3. Remaining work = 1 - 2/3 = 1/3. Time taken by B = (1/3) / (1/15) = 5 days.",
    category: "Quantitative Aptitude",
    topic: "Time and Work",
    difficulty: "medium",
  },
  {
    question: "A train 150 meters long passes a telegraph pole in 10 seconds. What is the speed of the train in km/h?",
    options: ["36 km/h", "45 km/h", "54 km/h", "72 km/h"],
    correctAnswer: 2,
    explanation: "Speed in m/s = Distance / Time = 150 / 10 = 15 m/s. Speed in km/h = 15 * (18 / 5) = 54 km/h.",
    category: "Quantitative Aptitude",
    topic: "Time, Speed and Distance",
    difficulty: "easy",
  },
  {
    question: "A man travels at 40 km/h for the first half of a distance and at 60 km/h for the second half. What is his average speed for the whole journey?",
    options: ["48 km/h", "50 km/h", "52 km/h", "54 km/h"],
    correctAnswer: 0,
    explanation: "Average speed for equal distances = (2 * v1 * v2) / (v1 + v2) = (2 * 40 * 60) / (40 + 60) = 4800 / 100 = 48 km/h.",
    category: "Quantitative Aptitude",
    topic: "Time, Speed and Distance",
    difficulty: "medium",
  },
  {
    question: "Two unbiased coins are tossed simultaneously. What is the probability of getting at least one head?",
    options: ["1/4", "1/2", "3/4", "1"],
    correctAnswer: 2,
    explanation: "Sample space S = {HH, HT, TH, TT} (total 4). Favorable outcomes for at least 1 head = {HH, HT, TH} (3 outcomes). P = 3/4.",
    category: "Quantitative Aptitude",
    topic: "Probability",
    difficulty: "easy",
  },
  {
    question: "From a standard deck of 52 playing cards, one card is drawn at random. What is the probability of getting a King or a Queen?",
    options: ["1/13", "2/13", "1/4", "4/13"],
    correctAnswer: 1,
    explanation: "Number of Kings = 4, Queens = 4. Total favorable = 8. Probability = 8 / 52 = 2 / 13.",
    category: "Quantitative Aptitude",
    topic: "Probability",
    difficulty: "easy",
  },
  {
    question: "What is the unit digit of 7^105?",
    options: ["1", "3", "7", "9"],
    correctAnswer: 2,
    explanation: "Cyclicity of 7 is 4 (7, 9, 3, 1). 105 mod 4 = 1. Therefore, 7^105 ends with the same unit digit as 7^1, which is 7.",
    category: "Quantitative Aptitude",
    topic: "Number System",
    difficulty: "medium",
  },
  {
    question: "What is the smallest 4-digit number divisible by 12, 15, and 18?",
    options: ["1020", "1080", "1120", "1180"],
    correctAnswer: 1,
    explanation: "LCM(12, 15, 18) = 180. Smallest 4-digit number is 1000. 1000 / 180 = 5 with remainder 100. Smallest 4-digit multiple = 1000 + (180 - 100) = 1080.",
    category: "Quantitative Aptitude",
    topic: "Number System",
    difficulty: "medium",
  },
  {
    question: "A sum of money doubles itself in 8 years at simple interest. What is the rate of interest per annum?",
    options: ["10%", "12.5%", "15%", "20%"],
    correctAnswer: 1,
    explanation: "SI = Principal P (since Amount = 2P). SI = (P * R * T) / 100 => P = (P * R * 8) / 100 => R = 100 / 8 = 12.5%.",
    category: "Quantitative Aptitude",
    topic: "Simple Interest",
    difficulty: "easy",
  },
  {
    question: "Find the simple interest on $5,000 at 6% per annum for 3 years.",
    options: ["$600", "$800", "$900", "$1000"],
    correctAnswer: 2,
    explanation: "SI = (P * R * T) / 100 = (5000 * 6 * 3) / 100 = $900.",
    category: "Quantitative Aptitude",
    topic: "Simple Interest",
    difficulty: "easy",
  },
  {
    question: "Find the compound interest on $10,000 at 10% per annum for 2 years compounded annually.",
    options: ["$2000", "$2100", "$2200", "$2500"],
    correctAnswer: 1,
    explanation: "Amount = P * (1 + R/100)^n = 10000 * (1.1)^2 = 10000 * 1.21 = $12,100. Compound Interest = 12100 - 10000 = $2,100.",
    category: "Quantitative Aptitude",
    topic: "Compound Interest",
    difficulty: "easy",
  },
  {
    question: "The difference between Compound Interest and Simple Interest on a sum for 2 years at 5% per annum is $25. What is the principal sum?",
    options: ["$8,000", "$9,000", "$10,000", "$12,000"],
    correctAnswer: 2,
    explanation: "Difference for 2 years = P * (R / 100)^2. 25 = P * (5 / 100)^2 => 25 = P * (1 / 400) => P = 25 * 400 = $10,000.",
    category: "Quantitative Aptitude",
    topic: "Compound Interest",
    difficulty: "hard",
  },
  {
    question: "In how many different ways can the letters of the word 'LEADER' be arranged?",
    options: ["360", "720", "120", "180"],
    correctAnswer: 0,
    explanation: "Word LEADER has 6 letters where E appears twice. Total arrangements = 6! / 2! = 720 / 2 = 360 ways.",
    category: "Quantitative Aptitude",
    topic: "Permutation and Combination",
    difficulty: "medium",
  },
  {
    question: "Out of 7 consonants and 4 vowels, how many words of 3 consonants and 2 vowels can be formed?",
    options: ["210", "25,200", "5,040", "12,600"],
    correctAnswer: 1,
    explanation: "Number of ways to choose 3 consonants out of 7 = 7C3 = 35. Number of ways to choose 2 vowels out of 4 = 4C2 = 6. Total selections = 35 * 6 = 210. Arrangement of 5 chosen letters = 5! = 120. Total words = 210 * 120 = 25,200.",
    category: "Quantitative Aptitude",
    topic: "Permutation and Combination",
    difficulty: "hard",
  },
  {
    question: "A pipe can fill a tank in 6 hours and another pipe can empty it in 8 hours. If both pipes are opened together, how long will it take to fill the tank?",
    options: ["14 hours", "18 hours", "24 hours", "32 hours"],
    correctAnswer: 2,
    explanation: "Net filling rate per hour = 1/6 - 1/8 = (4 - 3) / 24 = 1/24. Therefore, it will take 24 hours to fill the tank completely.",
    category: "Quantitative Aptitude",
    topic: "Time and Work",
    difficulty: "easy",
  },
  {
    question: "What is the compound ratio of 2:3 and 4:5?",
    options: ["6:8", "8:15", "10:12", "15:8"],
    correctAnswer: 1,
    explanation: "Compound ratio of a:b and c:d is (a*c) : (b*d). Here, (2*4) : (3*5) = 8 : 15.",
    category: "Quantitative Aptitude",
    topic: "Ratio and Proportion",
    difficulty: "easy",
  },

  // =========================================================================
  // LOGICAL REASONING (25 Questions)
  // =========================================================================
  {
    question: "What comes next in the series: 3, 7, 15, 31, 63, ?",
    options: ["95", "115", "127", "129"],
    correctAnswer: 2,
    explanation: "Pattern: Each number is multiplied by 2 and added 1 (x * 2 + 1). 63 * 2 + 1 = 127.",
    category: "Logical Reasoning",
    topic: "Number Series",
    difficulty: "easy",
  },
  {
    question: "Find the missing term in the sequence: 2, 6, 12, 20, 30, 42, ?",
    options: ["52", "54", "56", "60"],
    correctAnswer: 2,
    explanation: "Pattern is n^2 + n or adding +4, +6, +8, +10, +12, +14. Next difference is +14 => 42 + 14 = 56.",
    category: "Logical Reasoning",
    topic: "Number Series",
    difficulty: "easy",
  },
  {
    question: "Identify the odd one out: 8, 27, 64, 100, 125, 216.",
    options: ["27", "64", "100", "125"],
    correctAnswer: 2,
    explanation: "All numbers are perfect cubes except 100 (2^3=8, 3^3=27, 4^3=64, 5^3=125, 6^3=216). 100 is 10^2.",
    category: "Logical Reasoning",
    topic: "Number Series",
    difficulty: "medium",
  },
  {
    question: "If 'COMPUTER' is coded as 'RFUVQNPC', how is 'MEDICINE' written in that code?",
    options: ["EOJDJEFM", "EOJDEJFM", "MFEJDJOE", "EOJEFJDM"],
    correctAnswer: 0,
    explanation: "Reverse the word and replace each letter with its next letter (+1 in alphabet): E->F, N->O, I->J, D->E, I->J, C->D, E->F, M->N, then swap first and last letters. Code for MEDICINE becomes EOJDJEFM.",
    category: "Logical Reasoning",
    topic: "Coding-Decoding",
    difficulty: "hard",
  },
  {
    question: "In a certain code language, 'BUILDING' is written as '41538597'. How is 'NIGHT' written in that code if digits correspond to letter ranks mod 10?",
    options: ["95786", "98576", "95876", "95768"],
    correctAnswer: 0,
    explanation: "N=14->9, I=9->5 (or direct map), G=7, H=8, T=20. Following the map given in code: N=9, I=5, G=7, H=8, T=6 -> 95786.",
    category: "Logical Reasoning",
    topic: "Coding-Decoding",
    difficulty: "medium",
  },
  {
    question: "Light : Blind :: Speech : ?",
    options: ["Deaf", "Dumb", "Sound", "Vibration"],
    correctAnswer: 1,
    explanation: "Absence of light or inability to see is Blindness; absence or inability to speak is being Dumb (Mute).",
    category: "Logical Reasoning",
    topic: "Analogy",
    difficulty: "easy",
  },
  {
    question: "Odometer is to Distance as Speedometer is to ?",
    options: ["Area", "Speed", "Weight", "Volume"],
    correctAnswer: 1,
    explanation: "Odometer measures Distance; Speedometer measures Speed.",
    category: "Logical Reasoning",
    topic: "Analogy",
    difficulty: "easy",
  },
  {
    question: "Pointing to a photograph, a man said, 'I have no brother or sister, but that man's father is my father's son.' Whose photograph was it?",
    options: ["His own", "His son's", "His father's", "His nephew's"],
    correctAnswer: 1,
    explanation: "Since the man has no brother or sister, 'my father's son' means the man himself. So, 'that man's father is ME'. Hence, the photograph is of his son.",
    category: "Logical Reasoning",
    topic: "Blood Relations",
    difficulty: "medium",
  },
  {
    question: "A is B's sister. C is B's mother. D is C's father. E is D's mother. How is A related to D?",
    options: ["Grandmother", "Granddaughter", "Daughter", "Mother"],
    correctAnswer: 1,
    explanation: "A and B are siblings. C is their mother. D is C's father. Thus, D is A's maternal grandfather, making A his granddaughter.",
    category: "Logical Reasoning",
    topic: "Blood Relations",
    difficulty: "easy",
  },
  {
    question: "A person starts walking North, turns right after 5 km, turns left after 3 km, and finally turns left and walks 5 km. In which direction is he from his starting point?",
    options: ["East", "West", "North", "South"],
    correctAnswer: 2,
    explanation: "Walking 5 km East, then 3 km North, then 5 km West puts him directly 3 km North of his starting point.",
    category: "Logical Reasoning",
    topic: "Direction Sense",
    difficulty: "easy",
  },
  {
    question: "Rahul walks 10 km South, turns right and walks 5 km, turns right again and walks 10 km. How far is he from his starting point?",
    options: ["5 km", "10 km", "15 km", "20 km"],
    correctAnswer: 0,
    explanation: "10 km South + 5 km West + 10 km North leaves him 5 km West from the starting point.",
    category: "Logical Reasoning",
    topic: "Direction Sense",
    difficulty: "easy",
  },
  {
    question: "Statements: All cats are dogs. All dogs are birds. Conclusions: I. All cats are birds. II. All birds are cats.",
    options: ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"],
    correctAnswer: 0,
    explanation: "Since Cats ⊆ Dogs and Dogs ⊆ Birds, Cats ⊆ Birds. All cats are birds (Conclusion I follows). All birds are cats does not necessarily follow.",
    category: "Logical Reasoning",
    topic: "Syllogism",
    difficulty: "easy",
  },
  {
    question: "Statements: Some books are pens. Some pens are pencils. Conclusions: I. Some books are pencils. II. No book is a pencil.",
    options: ["Only I follows", "Only II follows", "Either I or II follows", "Neither follows"],
    correctAnswer: 2,
    explanation: "Since there is no direct relation between books and pencils, either Conclusion I (Some books are pencils) or Conclusion II (No book is a pencil) must be true.",
    category: "Logical Reasoning",
    topic: "Syllogism",
    difficulty: "medium",
  },
  {
    question: "Five friends A, B, C, D, E are sitting in a row facing North. C is next to E, B is to the right of D, A is at extreme left. If E is in the middle, who is sitting next to A?",
    options: ["B", "C", "D", "E"],
    correctAnswer: 2,
    explanation: "Positions (1 to 5): 1 is A (extreme left), 3 is E (middle). C is next to E (so C is at 2 or 4). B is right of D (D at 2, B at 4/5). Order: A, D, C, E, B or A, D, E, C, B. Next to A is D.",
    category: "Logical Reasoning",
    topic: "Seating Arrangement",
    difficulty: "medium",
  },
  {
    question: "Six people P, Q, R, S, T, U sit in a circle facing center. P is opposite R. Q is to immediate left of P. Who is to immediate right of R?",
    options: ["Q", "S", "T", "U"],
    correctAnswer: 0,
    explanation: "P and R are opposite. Clockwise order facing center: P has Q on immediate left. Across the circle facing center, immediate right of R aligns with Q.",
    category: "Logical Reasoning",
    topic: "Seating Arrangement",
    difficulty: "medium",
  },
  {
    question: "If 3 + 2 = 15, 4 + 3 = 28, and 5 + 4 = 45, what is 6 + 5?",
    options: ["55", "66", "70", "77"],
    correctAnswer: 1,
    explanation: "Pattern: (a + b) * a => (3+2)*3 = 15, (4+3)*4 = 28, (5+4)*5 = 45. For 6 + 5: (6+5)*6 = 11 * 6 = 66.",
    category: "Logical Reasoning",
    topic: "Logical Puzzles",
    difficulty: "easy",
  },
  {
    question: "In a class of 45 students, A's rank is 15th from the top. What is A's rank from the bottom?",
    options: ["30th", "31st", "32nd", "33rd"],
    correctAnswer: 1,
    explanation: "Rank from bottom = Total students - Rank from top + 1 = 45 - 15 + 1 = 31st.",
    category: "Logical Reasoning",
    topic: "Logical Puzzles",
    difficulty: "easy",
  },
  {
    question: "If 'Red' is called 'Blue', 'Blue' is called 'White', 'White' is called 'Green', and 'Green' is called 'Yellow', what is the color of milk?",
    options: ["White", "Blue", "Green", "Yellow"],
    correctAnswer: 2,
    explanation: "The real color of milk is White. In this code language, 'White' is called 'Green'. So milk's color is Green.",
    category: "Logical Reasoning",
    topic: "Coding-Decoding",
    difficulty: "easy",
  },
  {
    question: "Find the missing number in the matrix: [[2, 4, 8], [3, 6, 18], [4, 8, ?]]",
    options: ["24", "32", "36", "64"],
    correctAnswer: 1,
    explanation: "Row pattern: 1st * 2nd = 3rd element. 2*4=8, 3*6=18. For 3rd row: 4 * 8 = 32.",
    category: "Logical Reasoning",
    topic: "Logical Puzzles",
    difficulty: "easy",
  },
  {
    question: "Look at this series: 80, 10, 70, 15, 60, ... What number should come next?",
    options: ["20", "25", "50", "55"],
    correctAnswer: 0,
    explanation: "Two alternating series: (80, 70, 60...) decreasing by 10, and (10, 15, 20...) increasing by 5. Next number belongs to 2nd series: 15 + 5 = 20.",
    category: "Logical Reasoning",
    topic: "Number Series",
    difficulty: "easy",
  },
  {
    question: "Complete the pattern: SCT, TCU, UDV, VEW, ___",
    options: ["WFX", "WFW", "XFY", "WFY"],
    correctAnswer: 0,
    explanation: "1st letters: S, T, U, V -> W. 2nd letters: C, C, D, E -> F. 3rd letters: T, U, V, W -> X. Result: WFX.",
    category: "Logical Reasoning",
    topic: "Coding-Decoding",
    difficulty: "medium",
  },
  {
    question: "Statements: All cars are vehicles. No vehicle is a boat. Conclusion: No car is a boat.",
    options: ["True / Follows", "False / Does not follow", "Cannot be determined", "Partially true"],
    correctAnswer: 0,
    explanation: "Since Cars are completely inside Vehicles, and Vehicles are completely disjoint from Boats, Cars are also disjoint from Boats. Conclusion follows.",
    category: "Logical Reasoning",
    topic: "Syllogism",
    difficulty: "easy",
  },
  {
    question: "A clock shows 3:00. What is the angle between the hour hand and minute hand?",
    options: ["45 degrees", "60 degrees", "90 degrees", "120 degrees"],
    correctAnswer: 2,
    explanation: "At 3:00, minute hand is at 12 and hour hand is at 3. Angle = 3 * 30 degrees = 90 degrees.",
    category: "Logical Reasoning",
    topic: "Logical Puzzles",
    difficulty: "easy",
  },
  {
    question: "If TOM = 48 and DICK = 27, what is HARRY?",
    options: ["50", "60", "70", "80"],
    correctAnswer: 2,
    explanation: "Sum of alphabetical positions: H(8) + A(1) + R(18) + R(18) + Y(25) = 8 + 1 + 18 + 18 + 25 = 70.",
    category: "Logical Reasoning",
    topic: "Coding-Decoding",
    difficulty: "medium",
  },
  {
    question: "Find the next letter in the series: A, C, F, J, O, ?",
    options: ["T", "U", "V", "W"],
    correctAnswer: 1,
    explanation: "Differences between position ranks: +2, +3, +4, +5, +6. O is 15th letter. 15 + 6 = 21st letter, which is U.",
    category: "Logical Reasoning",
    topic: "Number Series",
    difficulty: "medium",
  },

  // =========================================================================
  // VERBAL ABILITY (25 Questions)
  // =========================================================================
  {
    question: "Select the synonym of 'CANDID':",
    options: ["Deceptive", "Frank", "Secretive", "Arrogant"],
    correctAnswer: 1,
    explanation: "'Candid' means truthful, straightforward, and frank.",
    category: "Verbal Ability",
    topic: "Synonyms",
    difficulty: "easy",
  },
  {
    question: "Select the synonym of 'METICULOUS':",
    options: ["Careless", "Thorough", "Clumsy", "Hastily"],
    correctAnswer: 1,
    explanation: "'Meticulous' means showing great attention to detail; careful and thorough.",
    category: "Verbal Ability",
    topic: "Synonyms",
    difficulty: "easy",
  },
  {
    question: "Select the synonym of 'FRUGAL':",
    options: ["Extravagant", "Economical", "Generous", "Wasteful"],
    correctAnswer: 1,
    explanation: "'Frugal' means economical in use or spending; sparing.",
    category: "Verbal Ability",
    topic: "Synonyms",
    difficulty: "easy",
  },
  {
    question: "Select the antonym of 'BENEVOLENT':",
    options: ["Malevolent", "Kind", "Generous", "Helpful"],
    correctAnswer: 0,
    explanation: "'Benevolent' means well-meaning and kindly. Its antonym is 'Malevolent' (wishing evil to others).",
    category: "Verbal Ability",
    topic: "Antonyms",
    difficulty: "easy",
  },
  {
    question: "Select the antonym of 'OBSOLETE':",
    options: ["Outdated", "Modern", "Ancient", "Archaic"],
    correctAnswer: 1,
    explanation: "'Obsolete' means no longer produced or used. Its antonym is 'Modern'.",
    category: "Verbal Ability",
    topic: "Antonyms",
    difficulty: "easy",
  },
  {
    question: "Select the antonym of 'EPHEMERAL':",
    options: ["Transient", "Permanent", "Short-lived", "Fleeting"],
    correctAnswer: 1,
    explanation: "'Ephemeral' means lasting for a very short time. Its antonym is 'Permanent'.",
    category: "Verbal Ability",
    topic: "Antonyms",
    difficulty: "medium",
  },
  {
    question: "Choose the correct verb form: 'Neither the manager nor the employees _____ present at the meeting.'",
    options: ["was", "were", "is", "has been"],
    correctAnswer: 1,
    explanation: "When subjects are connected by 'neither... nor', the verb agrees with the subject closest to it ('employees' is plural, so 'were').",
    category: "Verbal Ability",
    topic: "Grammar",
    difficulty: "medium",
  },
  {
    question: "Identify the part containing an error: 'He is senior than me in the organization.'",
    options: ["He is", "senior than", "me in the", "organization"],
    correctAnswer: 1,
    explanation: "Adjectives like senior, junior, superior, inferior take the preposition 'to' instead of 'than'. Correct phrasing: 'senior to me'.",
    category: "Verbal Ability",
    topic: "Sentence Correction",
    difficulty: "medium",
  },
  {
    question: "Fill in the blank: 'She has been working on this project _____ three months.'",
    options: ["since", "for", "from", "during"],
    correctAnswer: 1,
    explanation: "'For' is used to denote a duration of time ('three months'), whereas 'since' denotes a specific starting point.",
    category: "Verbal Ability",
    topic: "Grammar",
    difficulty: "easy",
  },
  {
    question: "Fill in the blank: 'If I _____ you, I would accept the job offer immediately.'",
    options: ["was", "were", "am", "have been"],
    correctAnswer: 1,
    explanation: "Subjunctive mood expressing a hypothetical situation uses 'were' for all pronouns ('If I were you').",
    category: "Verbal Ability",
    topic: "Grammar",
    difficulty: "easy",
  },
  {
    question: "What does the idiom 'Burn the midnight oil' mean?",
    options: ["Waste energy", "Work late into the night", "Cause a fire", "Spend money recklessly"],
    correctAnswer: 1,
    explanation: "'Burn the midnight oil' means to study or work late into the night.",
    category: "Verbal Ability",
    topic: "Vocabulary",
    difficulty: "easy",
  },
  {
    question: "What does the idiom 'Bite the bullet' mean?",
    options: ["Eat something hard", "Face a difficult situation with courage", "Avoid taking action", "Express anger"],
    correctAnswer: 1,
    explanation: "'Bite the bullet' means to endure a painful or difficult situation that is unavoidable.",
    category: "Verbal Ability",
    topic: "Vocabulary",
    difficulty: "easy",
  },
  {
    question: "Select the correctly spelled word:",
    options: ["Accomodate", "Accommodate", "Acommodate", "Accommodat"],
    correctAnswer: 1,
    explanation: "The correct spelling is 'Accommodate' with double 'c' and double 'm'.",
    category: "Verbal Ability",
    topic: "Vocabulary",
    difficulty: "easy",
  },
  {
    question: "Select the correctly spelled word:",
    options: ["Perseverance", "Perseverence", "Persiverance", "Perseverancee"],
    correctAnswer: 0,
    explanation: "The correct spelling is 'Perseverance' (ends in -ance).",
    category: "Verbal Ability",
    topic: "Vocabulary",
    difficulty: "medium",
  },
  {
    question: "Choose the best one-word substitution for: 'One who knows everything.'",
    options: ["Omnipresent", "Omniscient", "Omnipotent", "Optimist"],
    correctAnswer: 1,
    explanation: "'Omniscient' means all-knowing. 'Omnipresent' means present everywhere. 'Omnipotent' means all-powerful.",
    category: "Verbal Ability",
    topic: "Reading Comprehension",
    difficulty: "easy",
  },
  {
    question: "Choose the best one-word substitution for: 'A person who looks at the bright side of things.'",
    options: ["Pessimist", "Optimist", "Altruist", "Philanthropist"],
    correctAnswer: 1,
    explanation: "An 'Optimist' is a person who tends to be hopeful and confident about the future.",
    category: "Verbal Ability",
    topic: "Vocabulary",
    difficulty: "easy",
  },
  {
    question: "Sentence Correction: 'She didn't knew the answer to the question.'",
    options: ["didn't know", "didn't known", "hasn't know", "don't know"],
    correctAnswer: 0,
    explanation: "The auxiliary verb 'did/didn't' must be followed by the base form of the verb ('know').",
    category: "Verbal Ability",
    topic: "Sentence Correction",
    difficulty: "easy",
  },
  {
    question: "Complete the sentence: 'Hardly had I reached the station _____ the train departed.'",
    options: ["than", "when", "then", "after"],
    correctAnswer: 1,
    explanation: "'Hardly... when' and 'Scarcely... when' are correlative conjunction pairs. 'No sooner... than' uses 'than'.",
    category: "Verbal Ability",
    topic: "Grammar",
    difficulty: "medium",
  },
  {
    question: "Rearrange parts to form a coherent sentence: P: technology has evolved Q: over the past decade R: rapidly S: in education",
    options: ["P-R-Q-S", "Q-P-S-R", "P-S-R-Q", "R-P-Q-S"],
    correctAnswer: 0,
    explanation: "Logical order: 'P: technology has evolved R: rapidly Q: over the past decade S: in education'.",
    category: "Verbal Ability",
    topic: "Para Jumbles",
    difficulty: "medium",
  },
  {
    question: "Rearrange parts to form a coherent sentence: P: a healthy mind Q: resides R: in a S: healthy body",
    options: ["P-Q-R-S", "Q-P-R-S", "R-S-P-Q", "P-R-Q-S"],
    correctAnswer: 0,
    explanation: "Logical proverb sequence: 'P: a healthy mind Q: resides R: in a S: healthy body'.",
    category: "Verbal Ability",
    topic: "Para Jumbles",
    difficulty: "easy",
  },
  {
    question: "Fill in the blank: 'The committee _____ unanimous in its decision.'",
    options: ["was", "were", "are", "have been"],
    correctAnswer: 0,
    explanation: "When a collective noun like 'committee' acts as a single unified body, it takes a singular verb ('was').",
    category: "Verbal Ability",
    topic: "Grammar",
    difficulty: "medium",
  },
  {
    question: "Choose the correct passive form of: 'Who wrote this book?'",
    options: ["By whom was this book written?", "Who was written this book?", "By whom this book was written?", "Whom wrote this book?"],
    correctAnswer: 0,
    explanation: "Active interrogative 'Who wrote X?' transforms into passive 'By whom was X written?'.",
    category: "Verbal Ability",
    topic: "Grammar",
    difficulty: "medium",
  },
  {
    question: "Choose the antonym of 'TRANSPARENT':",
    options: ["Clear", "Opaque", "Lucid", "Translucent"],
    correctAnswer: 1,
    explanation: "'Transparent' means allowing light to pass through clearly. Its antonym is 'Opaque' (not transparent).",
    category: "Verbal Ability",
    topic: "Antonyms",
    difficulty: "easy",
  },
  {
    question: "Choose the synonym of 'PRAGMATIC':",
    options: ["Theoretical", "Practical", "Idealistic", "Unrealistic"],
    correctAnswer: 1,
    explanation: "'Pragmatic' means dealing with things sensibly and realistically; practical.",
    category: "Verbal Ability",
    topic: "Synonyms",
    difficulty: "easy",
  },
  {
    question: "Select the correct one-word substitution: 'A remedy for all diseases or difficulties.'",
    options: ["Panacea", "Antidote", "Antibiotic", "Elixir"],
    correctAnswer: 0,
    explanation: "'Panacea' is a solution or remedy for all difficulties or diseases.",
    category: "Verbal Ability",
    topic: "Vocabulary",
    difficulty: "easy",
  },

  // =========================================================================
  // TECHNICAL FUNDAMENTALS (25 Questions)
  // =========================================================================
  {
    question: "Which Object-Oriented Programming (OOP) principle allows a subclass to provide a specific implementation of a method that is already defined in its superclass?",
    options: ["Encapsulation", "Method Overriding", "Method Overloading", "Abstraction"],
    correctAnswer: 1,
    explanation: "Method Overriding allows a subclass to redefine a method of its superclass with the same signature to achieve runtime polymorphism.",
    category: "Technical Fundamentals",
    topic: "OOP",
    difficulty: "easy",
  },
  {
    question: "Which OOP concept enforces hiding internal implementation details and exposing only necessary functionality through public interfaces?",
    options: ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
    correctAnswer: 2,
    explanation: "Encapsulation restricts direct access to an object's state and bundles data with methods operating on that data.",
    category: "Technical Fundamentals",
    topic: "OOP",
    difficulty: "easy",
  },
  {
    question: "Can an abstract class in languages like C++ or Java contain concrete (implemented) methods?",
    options: ["Yes", "No", "Only in C++", "Only static methods"],
    correctAnswer: 0,
    explanation: "Yes, an abstract class can contain both abstract methods (without body) and concrete methods (with implementation).",
    category: "Technical Fundamentals",
    topic: "OOP",
    difficulty: "easy",
  },
  {
    question: "Which Normal Form in DBMS eliminates partial functional dependencies (where a non-key field depends on only part of a composite primary key)?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    correctAnswer: 1,
    explanation: "Second Normal Form (2NF) requires a relation to be in 1NF and have no partial functional dependencies.",
    category: "Technical Fundamentals",
    topic: "DBMS",
    difficulty: "medium",
  },
  {
    question: "Which SQL clause is used to filter group results AFTER an aggregate GROUP BY query has been executed?",
    options: ["WHERE", "HAVING", "ORDER BY", "FILTER"],
    correctAnswer: 1,
    explanation: "WHERE filters rows before grouping; HAVING filters aggregated group results after GROUP BY.",
    category: "Technical Fundamentals",
    topic: "SQL",
    difficulty: "easy",
  },
  {
    question: "Which SQL JOIN returns all records from the left table, and matched records from the right table?",
    options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
    correctAnswer: 1,
    explanation: "LEFT JOIN (or LEFT OUTER JOIN) returns all rows from the left table and matched rows from the right table; NULLs fill unmatched right rows.",
    category: "Technical Fundamentals",
    topic: "SQL",
    difficulty: "easy",
  },
  {
    question: "Which ACID property guarantees that all operations within a database transaction complete successfully, or none of them take effect at all?",
    options: ["Atomicity", "Consistency", "Isolation", "Durability"],
    correctAnswer: 0,
    explanation: "Atomicity ensures 'all-or-nothing' execution for database transactions.",
    category: "Technical Fundamentals",
    topic: "DBMS",
    difficulty: "easy",
  },
  {
    question: "Which CPU scheduling algorithm can potentially lead to starvation for long, resource-heavy processes?",
    options: ["Round Robin", "Shortest Job First (SJF)", "First Come First Served (FCFS)", "FIFO"],
    correctAnswer: 1,
    explanation: "SJF prioritizes short processes. If short processes continuously arrive, long processes may starve indefinitely.",
    category: "Technical Fundamentals",
    topic: "Operating Systems",
    difficulty: "medium",
  },
  {
    question: "Which condition for deadlock occurs when a process holds at least one resource and is waiting to acquire additional resources held by other processes?",
    options: ["Mutual Exclusion", "Hold and Wait", "No Preemption", "Circular Wait"],
    correctAnswer: 1,
    explanation: "The 'Hold and Wait' condition occurs when a process holding resources requests additional resources currently held by others.",
    category: "Technical Fundamentals",
    topic: "Operating Systems",
    difficulty: "medium",
  },
  {
    question: "What is Virtual Memory in modern Operating Systems?",
    options: ["Physical RAM memory stick", "A memory management technique creating the illusion of a larger main memory using secondary storage", "High-speed L1/L2 cache", "Read-Only Memory"],
    correctAnswer: 1,
    explanation: "Virtual Memory extends usable memory by mapping virtual addresses to physical RAM and secondary disk storage (paging/swapping).",
    category: "Technical Fundamentals",
    topic: "Operating Systems",
    difficulty: "easy",
  },
  {
    question: "What is 'Thrashing' in an Operating System?",
    options: ["High CPU efficiency", "High page fault rate where OS spends more time swapping pages than executing instructions", "Disk formatting state", "Deadlock detection mode"],
    correctAnswer: 1,
    explanation: "Thrashing occurs when main memory is overcommitted, causing continuous page faults and excessive swapping between RAM and disk.",
    category: "Technical Fundamentals",
    topic: "Operating Systems",
    difficulty: "medium",
  },
  {
    question: "At which layer of the OSI model does the Internet Protocol (IP) operate?",
    options: ["Data Link Layer", "Network Layer", "Transport Layer", "Application Layer"],
    correctAnswer: 1,
    explanation: "IP operates at Layer 3 (Network Layer) of the OSI model, handling packet routing and addressing.",
    category: "Technical Fundamentals",
    topic: "Computer Networks",
    difficulty: "easy",
  },
  {
    question: "Which Transport Layer protocol provides reliable, connection-oriented, ordered data transmission with flow and congestion control?",
    options: ["UDP", "IP", "TCP", "ICMP"],
    correctAnswer: 2,
    explanation: "TCP (Transmission Control Protocol) is connection-oriented and guarantees reliable data delivery, unlike connectionless UDP.",
    category: "Technical Fundamentals",
    topic: "Computer Networks",
    difficulty: "easy",
  },
  {
    question: "What is the primary function of the Domain Name System (DNS)?",
    options: ["Assign dynamic IP addresses", "Translate human-readable domain names into IP addresses", "Encrypt HTTP traffic", "Route data packets over local networks"],
    correctAnswer: 1,
    explanation: "DNS acts as the internet's phonebook, mapping domain names (e.g., example.com) to numeric IP addresses.",
    category: "Technical Fundamentals",
    topic: "Computer Networks",
    difficulty: "easy",
  },
  {
    question: "Which default port number is used for secure web communication over HTTPS?",
    options: ["80", "21", "443", "8080"],
    correctAnswer: 2,
    explanation: "Port 443 is the standard port for HTTPS encrypted traffic; port 80 is used for HTTP.",
    category: "Technical Fundamentals",
    topic: "Computer Networks",
    difficulty: "easy",
  },
  {
    question: "What is the worst-case time complexity of searching for a value in a balanced Binary Search Tree (BST)?",
    options: ["O(1)", "O(log N)", "O(N)", "O(N log N)"],
    correctAnswer: 1,
    explanation: "In a balanced BST, tree height is log(N), making search, insertion, and deletion O(log N) worst-case.",
    category: "Technical Fundamentals",
    topic: "Data Structures",
    difficulty: "easy",
  },
  {
    question: "Which data structure operates strictly on the LIFO (Last In First Out) principle?",
    options: ["Queue", "Stack", "Linked List", "Heap"],
    correctAnswer: 1,
    explanation: "A Stack follows Last In First Out (LIFO). Elements pushed last are popped first.",
    category: "Technical Fundamentals",
    topic: "Data Structures",
    difficulty: "easy",
  },
  {
    question: "In a Max Heap of size N, where is the maximum element always located?",
    options: ["At the root (index 0)", "At the last leaf node", "At index N/2", "At any leaf node"],
    correctAnswer: 0,
    explanation: "By definition of a Max Heap, every parent node is greater than or equal to its children, placing the maximum element at the root.",
    category: "Technical Fundamentals",
    topic: "Data Structures",
    difficulty: "easy",
  },
  {
    question: "What is the time complexity of pushing an element onto a Stack backed by a dynamic array (amortized)?",
    options: ["O(1)", "O(log N)", "O(N)", "O(N^2)"],
    correctAnswer: 0,
    explanation: "Pushing onto a stack is an O(1) constant time operation (amortized O(1) for dynamic arrays).",
    category: "Technical Fundamentals",
    topic: "Data Structures",
    difficulty: "easy",
  },
  {
    question: "What is the average time complexity of the Quick Sort algorithm?",
    options: ["O(N)", "O(N log N)", "O(N^2)", "O(2^N)"],
    correctAnswer: 1,
    explanation: "Quick Sort has an average time complexity of O(N log N), though its worst-case (with poor pivot choice) is O(N^2).",
    category: "Technical Fundamentals",
    topic: "Algorithms",
    difficulty: "easy",
  },
  {
    question: "Which sorting algorithm guarantees O(N log N) time complexity in the worst-case and is stable?",
    options: ["Quick Sort", "Merge Sort", "Bubble Sort", "Selection Sort"],
    correctAnswer: 1,
    explanation: "Merge Sort consistently runs in O(N log N) time across best, average, and worst cases, and preserves relative order of equal elements (stable).",
    category: "Technical Fundamentals",
    topic: "Algorithms",
    difficulty: "easy",
  },
  {
    question: "Which search algorithm requires the input collection to be sorted beforehand?",
    options: ["Linear Search", "Binary Search", "Depth First Search", "Breadth First Search"],
    correctAnswer: 1,
    explanation: "Binary Search relies on sorted order to divide the search space in half at each step.",
    category: "Technical Fundamentals",
    topic: "Algorithms",
    difficulty: "easy",
  },
  {
    question: "In C/C++, what happens when a program accesses an array index outside its declared bound?",
    options: ["Compilation error", "IndexOutOfBoundsException thrown", "Undefined Behavior", "Automatic array resize"],
    correctAnswer: 2,
    explanation: "C and C++ do not perform automatic array bounds checking; out-of-bounds access results in Undefined Behavior.",
    category: "Technical Fundamentals",
    topic: "Programming fundamentals",
    difficulty: "medium",
  },
  {
    question: "What does the term 'Recursion' mean in programming?",
    options: ["An infinite while loop", "A function calling itself directly or indirectly", "Overriding a method in a child class", "Executing asynchronous promises"],
    correctAnswer: 1,
    explanation: "Recursion occurs when a function solves a problem by calling itself on smaller sub-problems until a base condition is met.",
    category: "Technical Fundamentals",
    topic: "Programming fundamentals",
    difficulty: "easy",
  },
  {
    question: "What is the auxiliary space complexity of an iterative Binary Search implementation?",
    options: ["O(1)", "O(log N)", "O(N)", "O(N log N)"],
    correctAnswer: 0,
    explanation: "Iterative Binary Search uses only a few pointers (low, high, mid), requiring O(1) constant auxiliary space.",
    category: "Technical Fundamentals",
    topic: "Algorithms",
    difficulty: "easy",
  },
];

async function seedAptitudeQuestions() {
  try {
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) {
      throw new Error("MONGODB_URI environment variable is missing!");
    }

    console.log("Connecting to MongoDB...");
    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB successfully.");

    console.log(`Preparing to seed ${initialQuestions.length} aptitude questions...`);

    // Idempotent upsert operations: match by question text and category
    const bulkOps = initialQuestions.map((q) => ({
      updateOne: {
        filter: { question: q.question, category: q.category },
        update: { $set: { ...q, isActive: true } },
        upsert: true,
      },
    }));

    const result = await AptitudeQuestion.bulkWrite(bulkOps);

    console.log("Seed Completed Successfully!");
    console.log(`- Matched / Updated: ${result.matchedCount}`);
    console.log(`- Newly Inserted: ${result.upsertedCount}`);
    console.log(`- Total Questions Processed: ${initialQuestions.length}`);

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error("Error seeding aptitude questions:", error);
    process.exit(1);
  }
}

seedAptitudeQuestions();
